### PR TITLE
Add support to new regions

### PR DESCRIPTION
**Pull request by ianrodrigues**
I'm not sure that's the best way to validate regions, but I've added some missing regions.

PS.: That's my first Golang PR :tada:

### CODE REVIEW

**Comment by jritsema** [comment]
Hi @ianrodrigues, this looks great!  Thanks for submitting.  

A couple of things.  Would you mind excluding the `Gopkg.lock` changes?  These shouldn't be needed to support the region change.  Also, would you mind targeting this PR at the develop branch?  Thanks.

**Comment by ianrodrigues** [comment]
Hey @jritsema , sorry for the delay. I did fix my PR, hope it works now. Thanks!

**Comment by jritsema** [comment]
@ianrodrigues version `v0.6.0-pre-4-g7d97b8e` is now available with your changes here until we cut the next master release.

```
curl -s beta.get-fargate.turnerlabs.io | sh
```

**Comment by niklasbeinghaus** [comment]
Meh, this still doesn't seem to work?
Calling
`fargate service deploy -f docker-compose.yml --region eu-central-1` gives me:
`[!] Invalid region: eu-central-1 [valid regions: us-east-1, us-east-2, us-west-1, us-west-2, ca-central-1, eu-west-1, eu-west-2, eu-central-1, ap-southeast-1, ap-southeast-2, ap-northeast-1, ap-northheast-2, ap-south-1]`

**Comment by jritsema** [comment]
@niklasbeinghaus I see the bug :(   I can patch it after we merge the secrets PR (hopefully today).

**Comment by jritsema** [comment]
here's a patch: #44

**Comment by jritsema** [comment]
Please try the latest pre-release build and let me now.
```
curl -s beta.get-fargate.turnerlabs.io | sh
```

**Pull request merged**
