### PR TITLE
updates to turnerlabs and removes unnecessary cmds

### PR DESCRIPTION
**Pull request by jritsema**

### CODE REVIEW

**Comment by jritsema** [comment]
Good catch @wilsonodk.  How's this?

**Comment by wilsonodk** [comment]
@jritsema Looks like some of the links in the contributing document aren't working correctly.

**Comment by lukeburns** [comment]
Why is `fargate service create` unnecessary? Is this cli just for managing existing services?

**Comment by jritsema** [comment]
Hi @lukeburns.  Yes, we prefer using IaC tools for managing [what we consider to be] the infrastructure components.  This CLI is focused on the "application" concerns like deploying images, environment variables, and secrets on top of infrastructure and managing running applications (ps, logs, restart, etc).  

Our strategy has been to use Terraform templates like [these](https://github.com/turnerlabs/fargate-create#stacks) for provisioning different types of infrastructure stacks.

Our [fargate-create](https://github.com/turnerlabs/fargate-create) CLI tool brings these infrastructure and application components together and lets you provision new apps.

Does that make sense?

**Pull request merged**
