### PR TITLE
Support for multiple containers in `service deploy` and `task register` commands

### PR DESCRIPTION
**Pull request by ajliv**
Adds support for deploying/registering multiple container definitions.

Any service in the docker-compose.yml can be skipped if given the label "aws.ecs.fargate.ignore" with a value of `1`. Only container definitions that exist in the previous task revision will be updated.

Each service name in the docker compose file will be used as the container definition
name. Note that the image, environments variables, and secrets are replaced with what's in the
compose file. 

The presence of the `aws.ecs.fargate.deploy: 1` label or a docker-compose file with one container will allow backwards compatibility.

**docker-compose.yml**

```yaml
version: '3.7'
services:
  frontend:
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/my-app:0.1.0
    environment:
      PORT: 3000
  backend:
    image: 1234567890.dkr.ecr.us-east-1.amazonaws.com/my-backend:0.2.0
    environment:
      PORT: 4000
  redis:
    image: redis
    labels:
      aws.ecs.fargate.ignore: 1
```

```
$ fargate service deploy -f docker-compose.yml --wait-for-service

[i] Deployed revision 22 to service my-app-dev
[i] Waiting for service my-app-dev to reach a steady state...
[i] Service my-app-dev has reached a steady state.
```

### CODE REVIEW

**Comment by twelvelabs** [comment]
Excited to see this as I have a service that needs a sidecar added. I was worried I would have to move away from this tool. Thank you!

One suggestion. Instead of another command, what do you think about tweaking the existing “service deploy” command so that it supports multiple containers? Right now it looks for the first labeled compose service. It could be changed to look for all services with that label. Just thinking it might be confusing to have two commands that seem so similar.

Regardless, happy to see this in either form. Thanks again!

**Comment by jritsema** [comment]
I agree with @twelvelabs regarding having `service deploy` handle multiple containers versus introducing a new command.  It seems like we could handle this in a non-breaking way and I can't really think of any downsides.  We should also think about multi-container support for some of the other commands like `info`, `logs`, `env`, `ps`, etc., to round out the experience.  Perhaps, those could be handled in separate PRs.

**Comment by ajliv** [comment]
Initially I didn't want to add any extra complexity to`deploy` but I agree it could be merged into that command. 

My biggest concern about backwards compatibility is the new functionality will change container names in the task definition based on the name in the docker-compose file. For someone upgrading, it could unexpectedly mess up the LB association. Will have to think of the best way to avoid that.

**Comment by ajliv** [comment]
Updated to add this as a `--compose-all` flag on the `service deploy` and `task register` commands. Had to refactor some of the methods that convert docker services into container definitions shared by both commands, but current behavior should remain the same when the flag isn't passed

**Comment by rafaelsiqueira** [comment]
Hi! Is this PR is still working progress? I'm really interested on this. Let me know if can help with something to have it done.

Cheers.

**Pull request closed without merging**
